{{- if and .Values.backend.enabled .Values.backend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mypythonproject1.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mypythonproject1.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  minAvailable: {{ .Values.backend.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "mypythonproject1.backendSelectorLabels" . | nindent 6 }}
{{- end }}
