{{- if and .Values.backend.enabled .Values.backend.secretsManager.enabled .Values.backend.secretsManager.objects }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.backend.secretsManager.secretProviderClass }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mypythonproject1.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  provider: aws
  parameters:
    objects: |
      {{- range .Values.backend.secretsManager.objects }}
      - objectName: {{ .secretArn | quote }}
        objectType: "secretsmanager"
        {{- if .jmesPath }}
        jmesPath:
          {{- range .jmesPath }}
          - path: {{ .path | quote }}
            objectAlias: {{ .objectAlias | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
  secretObjects:
    - secretName: {{ include "mypythonproject1.fullname" . }}-backend-secrets
      type: Opaque
      data:
        {{- range .Values.backend.secretsManager.objects }}
        {{- range .jmesPath }}
        - objectName: {{ .objectAlias | quote }}
          key: {{ .objectAlias | quote }}
        {{- end }}
        {{- end }}
{{- end }}
